# 公開するページのURL
baseURL = "https://hmos.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "ブログ ささやかに"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "cmos"
    bio = "大学生"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#00a7db"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "CMos6666"
  github = "hcmos"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]
