# 公開するページのURL
baseURL = "https://blog.hcmos.jp"
publishDir = "docs"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

googleAnalytics = "G-D0L0TNFHKS"

# ブログのタイトル
title = "cmosのブログ"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "cmos"
    bio = "大学生"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "cmos"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#00a7db"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "CMos6666"
  github = "hcmos"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["recent", "categories", "taglist"]
